#!/usr/bin/env python3
"""Build deterministic embedded render-asset registry for Ocean Rescue.

Reads atlas-manifest.json, pixi-assets-manifest.json, and all declared files
to produce a frozen JavaScript registry at window.OceanRescue.RenderAssets.
"""

import argparse
import base64
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path


class RegistryError(Exception):
    """Registry build failure."""


def die(msg, code=1):
    print(f"REGISTRY ERROR: {msg}", file=sys.stderr)
    sys.exit(code)


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha256_file(path):
    return sha256_bytes(path.read_bytes())


def load_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        raise RegistryError(f"Cannot read {path}: {e}")


def deterministic_json(obj, indent=2):
    """Serialize JSON with deterministic key ordering."""
    return json.dumps(
        obj,
        sort_keys=True,
        ensure_ascii=True,
        separators=(",", ": "),
        indent=indent,
    )


def build_registry(atlas_dir, output_path):
    atlas_dir = Path(atlas_dir)
    output_path = Path(output_path)

    atlas_manifest_path = atlas_dir / "atlas-manifest.json"
    if not atlas_manifest_path.exists():
        raise RegistryError(f"atlas-manifest.json not found: {atlas_manifest_path}")

    pixi_manifest_path = atlas_dir / "pixi-assets-manifest.json"
    if not pixi_manifest_path.exists():
        raise RegistryError(
            f"pixi-assets-manifest.json not found: {pixi_manifest_path}"
        )

    atlas_manifest = load_json(atlas_manifest_path)
    pixi_manifest = load_json(pixi_manifest_path)

    atlas_manifest_sha = sha256_file(atlas_manifest_path)
    pixi_manifest_sha = sha256_file(pixi_manifest_path)

    bundles = atlas_manifest.get("bundles", [])
    if len(bundles) != 3:
        raise RegistryError(f"Expected 3 bundles in atlas-manifest, got {len(bundles)}")

    bundle_order = [b["name"] for b in bundles]

    declared_files = atlas_manifest.get("files", {})
    if not declared_files:
        raise RegistryError("No files declared in atlas-manifest.json")

    files = {}
    for rel_path in sorted(declared_files.keys()):
        full_path = atlas_dir / rel_path
        if not full_path.exists():
            raise RegistryError(f"Declared file missing: {rel_path}")

        actual_sha = sha256_file(full_path)
        expected_sha = declared_files[rel_path]
        if actual_sha != expected_sha:
            raise RegistryError(
                f"Hash mismatch for {rel_path}: "
                f"manifest={expected_sha}, actual={actual_sha}"
            )

        if rel_path.endswith(".json"):
            text = full_path.read_text(encoding="utf-8")
            files[rel_path] = {
                "mime": "application/json",
                "sha256": actual_sha,
                "text": text,
            }
        elif rel_path.endswith(".png"):
            raw = full_path.read_bytes()
            b64 = base64.b64encode(raw).decode("ascii")
            files[rel_path] = {
                "mime": "image/png",
                "sha256": actual_sha,
                "dataUri": f"data:image/png;base64,{b64}",
            }
        else:
            raise RegistryError(f"Unsupported file type in atlas: {rel_path}")

    registry = {
        "schemaVersion": 1,
        "atlasManifestSha256": atlas_manifest_sha,
        "pixiAssetsManifestSha256": pixi_manifest_sha,
        "bundleOrder": bundle_order,
        "atlasManifest": atlas_manifest,
        "pixiAssetsManifest": pixi_manifest,
        "files": files,
    }

    js_lines = []
    js_lines.append("// Auto-generated by build_render_assets_registry.py")
    js_lines.append("// DO NOT EDIT")
    js_lines.append("")
    js_lines.append("(function() {")
    js_lines.append('  "use strict";')
    js_lines.append("")
    js_lines.append("  var registry = " + deterministic_json(registry, indent=4) + ";")
    js_lines.append("")
    js_lines.append("  function deepFreeze(obj) {")
    js_lines.append("    if (obj === null || typeof obj !== 'object') return obj;")
    js_lines.append("    Object.freeze(obj);")
    js_lines.append("    Object.keys(obj).forEach(function(key) {")
    js_lines.append("      deepFreeze(obj[key]);")
    js_lines.append("    });")
    js_lines.append("    return obj;")
    js_lines.append("  }")
    js_lines.append("")
    js_lines.append("  deepFreeze(registry);")
    js_lines.append("")
    js_lines.append("  window.OceanRescue = window.OceanRescue || {};")
    js_lines.append("  window.OceanRescue.RenderAssets = registry;")
    js_lines.append("})();")
    js_lines.append("")

    js_content = "\n".join(js_lines)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    fd, tmp_path = tempfile.mkstemp(
        dir=str(output_path.parent),
        prefix=".registry_",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(js_content)
        os.replace(tmp_path, output_path)
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)

    print(f"Registry written: {output_path}")
    print(f"  Atlas manifest SHA-256: {atlas_manifest_sha}")
    print(f"  Pixi manifest SHA-256: {pixi_manifest_sha}")
    print(f"  Bundle order: {bundle_order}")
    print(f"  Embedded files: {len(files)}")


def main():
    parser = argparse.ArgumentParser(
        description="Build Ocean Rescue render-asset registry"
    )
    parser.add_argument(
        "--atlas-dir",
        required=True,
        help="Path to generated atlas directory",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to output JS file",
    )
    args = parser.parse_args()

    try:
        build_registry(args.atlas_dir, args.output)
    except RegistryError as e:
        die(str(e))


if __name__ == "__main__":
    main()
